### ISSUE TITLE
Phase 2 Requirements 

### ISSUE THREAD

**Issue by stellae13** [stellae13/CGullProject#65]
- [x] Optimization of C# fundamentals 
- [x] Well organized class structure
- [x] Enhanced use of 2 collection constructs
- [x] Cart/CreateNewCart(cartName) post endpoint
- [x] Cart/RemoveItem(cartId, itemId) delete endpoint
- [x] Inventory/UpdateStocks(itemId, quantity) put endpoint
- [x] Inventory/ChangePrice(itemId, price) put endpoint
- [x] Inventory/AddNewItem(item) post endpoint 
- [x] Demonstrate use of at least 2 LINQ Queries 
- [x] Utilize EF Core to create database 
- [x] Modularity - demonstration of OOP concepts + optimal use
- [x] Coding Techniques + Elegance comment, name, conventions demonstrated throughout consistently

**Comment by rleboeu** [comment]
Controllers and models reflect code convention

**Comment by stellae13** [comment]
i think we are good here, I will wait to close in case yall want to look over it more
